### PR TITLE
All Recipes get

### PR DESCRIPTION
**Pull request by amead99**
Recipes.jsx makes real get call. Chnaged rendering of the search bar so that it would work together with the all recipes list. Changed edit button on recipe card to render for admin only.

### CODE REVIEW

**Review by jared23m — APPROVED** [review]
I do not see edit button when logged in as admin like you said in the description but go for merge anyway

**Comment by amead99** [comment]
> I do not see edit button when logged in as admin like you said in the description but go for merge anyway

It's only on the allrecipes page right now, not on main page. Sorry forgot to clarify  I figured it  looks better that way, but I can add the edit button to main page if ppl want that

**Comment by jared23m** [comment]
> > I do not see edit button when logged in as admin like you said in the description but go for merge anyway
> 
> It's only on the allrecipes page right now, not on main page. Sorry forgot to clarify I figured it looks better that way, but I can add the edit button to main page if ppl want that

I just fetched again just in case but I am not seeing it on my allrecipes page when logged in as adminTest

**Review by ljreaux — APPROVED** [review]

**Review by BarryFullStack — APPROVED** [review]
approved once that search error is fixed

**Pull request merged**
