### PR TITLE
Fix Tag Filter

### PR DESCRIPTION
**Pull request by jared23m**
tag filter is fixed. I had to add one more state

### CODE REVIEW

**Review by ljreaux — APPROVED** [review]

**Review by BarryFullStack — APPROVED** [review]
It's working but we are gaining one extra blank tag at the end.

**Comment by jared23m** [comment]
Others must review. I'm not having that on my end and I was looking over the code of that component and everything looks normal it seems
checkboxes

**Comment by ljreaux** [comment]
I'm also not having that issue. could be a local db issue.

**Review by amead99 — APPROVED** [review]

**Comment by amead99** [comment]
I also didn't get the error

**Pull request merged**
